# -*- coding: utf-8 -*-
"""nluprob1(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14k--1W6KAG7S1O79dHbU47JoekSQ8pxn
"""

pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup
import os

# Create folder if not exists
os.makedirs("data/raw", exist_ok=True)

# --------------------------------------------------------------
# STEP 1: List of faculty URLs also other websites included in it
# ----------------------------------------------------------------
faculty_urls = [
    "https://www.iitj.ac.in/People/Profile/c7aa696c-0f3d-48aa-ad32-eeb189bdca60",
    "https://www.iitj.ac.in/People/Profile/9d7c7c5b-4ddf-487e-a00c-ab2c5878b9a4",
    "https://www.iitj.ac.in/People/Profile/bc795393-557c-4140-8c14-932a5953a6a1",
    "https://www.iitj.ac.in/People/Profile/e9793af3-6d4f-4560-8489-2c256912a72a",
    "https://www.iitj.ac.in/People/Profile/ec8b858c-7122-4046-8597-5a7871a10258",
    "https://www.iitj.ac.in/People/Profile/cbfae589-0b31-43d8-8a49-4990247e8628"
    "https://www.iitj.ac.in/People/List?dept=computer-science-engineering&c=1c8346b0-07a4-401e-bce0-7f571bb4fabd",
    "https://www.iitj.ac.in/People/List?dept=electrical-engineering&c=1c8346b0-07a4-401e-bce0-7f571bb4fabd",
    "https://www.iitj.ac.in/People/List?dept=mechanical-engineering&c=1c8346b0-07a4-401e-bce0-7f571bb4fabd",
    "https://www.iitj.ac.in/chemistry/en/chemistry",
    "https://www.iitj.ac.in/bioscience-bioengineering",
    "https://www.iitj.ac.in/computer-science-engineering/",
    "https://www.iitj.ac.in/office-of-research-development/en/office-of-research-and-development",
    "https://www.iitj.ac.in/crf/en/crf",
    "https://www.iitj.ac.in/aiot-fab-facility/en/aiot-fab-facility?",
    "https://www.iitj.ac.in/main/en/news?dsl=2&dslID=e68ae573-7d7e-4f5f-bf35-e3c801ac5f60",
    "https://www.iitj.ac.in/main/en/news?dsl=2&dslID=4cfae408-a661-456d-b259-82106d406d22",
    "https://www.iitj.ac.in/main/en/news?dsl=2&dslID=066573e2-e265-4f34-8e47-275cffbf4964",
    "https://www.iitj.ac.in/main/en/news?dsl=2&dslID=ef02db94-b6ab-4a3a-a067-c59051df42ab",
    "https://www.iitj.ac.in/main/en/news?dsl=2&dslID=50cb8410-2829-4b6b-a845-7499ff273f80"
]

# -------------------------------
# STEP 2: Function to extract clean text
# -------------------------------
def extract_faculty_text(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    # Remove scripts and styles
    for script in soup(["script", "style"]):
        script.extract()

    # Extract visible text
    text = soup.get_text(separator=" ")

    return text


# -------------------------------
# STEP 3: Save each profile
# -------------------------------
for i, url in enumerate(faculty_urls):

    print(f"Scraping: {url}")

    text = extract_faculty_text(url)

    with open(f"data/raw/faculty_{i+1}.txt", "w", encoding="utf-8") as f:
        f.write(text)

print("All faculty profiles saved!")

import os
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

# Create output folder
os.makedirs("data/processed", exist_ok=True)

# -------------------------------
# CLEAN TEXT FUNCTION
# -------------------------------
def clean_text(text):

    # Remove emails
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Lowercase
    text = text.lower()

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text


# -------------------------------
# Tokenizing and filtering
# -------------------------------
def tokenize_and_filter(text):

    tokens = word_tokenize(text)

    # Remove stopwords plus short words
    tokens = [
        word for word in tokens
        if word not in stop_words and len(word) > 2
    ]

    # Remove common IIT words
    remove_words = {"iit", "jodhpur", "india"}
    tokens = [word for word in tokens if word not in remove_words]

    return tokens


# -------------------------------
# PROCESS ALL FILES
# -------------------------------
input_folder = "data/raw/"
all_tokens = []

for file in os.listdir(input_folder):
    if file.endswith(".txt"):

        print(f"Processing: {file}")

        with open(os.path.join(input_folder, file), "r", encoding="utf-8") as f:
            text = f.read()

        # Clean and tokenize
        clean = clean_text(text)
        tokens = tokenize_and_filter(clean)

        # Save cleaned version of each file
        with open(f"data/processed/clean_{file}", "w", encoding="utf-8") as f:
            f.write(" ".join(tokens))

        all_tokens.extend(tokens)


# -------------------------------
# SAVE FINAL CORPUS
# -------------------------------
with open("data/processed/clean_corpus.txt", "w", encoding="utf-8") as f:
    f.write(" ".join(all_tokens))


# -------------------------------
# PRINT STATS
# -------------------------------
print("\n--- DATASET STATS ---")
print("Total Documents:", len(os.listdir(input_folder)))
print("Total Tokens:", len(all_tokens))
print("Vocabulary Size:", len(set(all_tokens)))

"""# Data Upload"""

from google.colab import files
uploaded = files.upload()

import os

os.makedirs("data/raw", exist_ok=True)

for file in uploaded.keys():
    os.rename(file, "data/raw/" + file)

"""# Dataset Description

The dataset was constructed using three sources:

Academic regulation documents (official IIT Jodhpur PDF)
Institutional website pages (departments, research, academic programs)
Faculty profile pages
"""

#Task1
import os
import re
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter

nltk.download('punkt')

# -------------------------------
# STEP 1: Load all text files
# -------------------------------
def load_data(folder_path):
    documents = []

    for file in os.listdir(folder_path):
        if file.endswith(".txt"):
            with open(os.path.join(folder_path, file), 'r', encoding='utf-8') as f:
                text = f.read()
                documents.append(text)

    return documents


# -------------------------------
# STEP 2: Clean text
# -------------------------------
def clean_text(text):

    # Remove boilerplate patterns (menus, navigation, etc.)
    text = re.sub(r'\n+', ' ', text)  # remove extra newlines
    text = re.sub(r'\s+', ' ', text)  # remove extra spaces

    # Remove non-English characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Lowercase
    text = text.lower()

    return text


# -------------------------------
# STEP 3: Tokenization
# -------------------------------
def tokenize_text(text):
    tokens = word_tokenize(text)

    # Remove very short tokens (like 'a', 'i')
    tokens = [word for word in tokens if len(word) > 2]

    return tokens


# -------------------------------
# STEP 4: Full preprocessing pipeline
# -------------------------------
def preprocess_corpus(documents):
    all_tokens = []
    cleaned_docs = []

    for doc in documents:
        clean_doc = clean_text(doc)
        tokens = tokenize_text(clean_doc)

        cleaned_docs.append(tokens)
        all_tokens.extend(tokens)

    return cleaned_docs, all_tokens


# -------------------------------
# STEP 5: Dataset statistics
# -------------------------------
def dataset_stats(cleaned_docs, all_tokens):

    num_docs = len(cleaned_docs)
    total_tokens = len(all_tokens)
    vocab_size = len(set(all_tokens))

    print(f"Total Documents: {num_docs}")
    print(f"Total Tokens: {total_tokens}")
    print(f"Vocabulary Size: {vocab_size}")

    return num_docs, total_tokens, vocab_size


# -------------------------------
# RUN PIPELINE
# -------------------------------
documents = load_data("data/raw/")
cleaned_docs, all_tokens = preprocess_corpus(documents)

dataset_stats(cleaned_docs, all_tokens)

"""# WORD CLOUD"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def generate_wordcloud(tokens):
    text = " ".join(tokens)

    wc = WordCloud(width=800, height=400, background_color='white').generate(text)

    plt.figure(figsize=(10,5))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.title("Word Cloud of IIT Jodhpur Corpus")
    plt.show()

generate_wordcloud(all_tokens)

"""# SAVE CLEAN CORPUS"""

with open("clean_corpus.txt", "w", encoding="utf-8") as f:
    for doc in cleaned_docs:
        f.write(" ".join(doc) + "\n")

"""# Task 2

# Objective

Train two Word2Vec models:

CBOW (Continuous Bag of Words)
Skip-gram with Negative Sampling

and analyze the effect of:

Embedding dimension
Context window size
Number of negative samples

# PREPARE DATA
"""

with open("data/processed/clean_corpus.txt", "r") as f:
    corpus = f.read().split()

"""# BUILD VOCABULARY"""

from collections import Counter

vocab = list(set(corpus))
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}
vocab_size = len(vocab)

"""# GENERATE TRAINING DATA : CBOW"""

def generate_cbow_data(corpus, window_size):
    data = []

    for i in range(window_size, len(corpus) - window_size):
        context = []

        for j in range(-window_size, window_size + 1):
            if j != 0:
                context.append(word2idx[corpus[i + j]])

        target = word2idx[corpus[i]]
        data.append((context, target))

    return data

"""# Skip-gram"""

def generate_skipgram_data(corpus, window_size):
    data = []

    for i in range(window_size, len(corpus) - window_size):
        target = word2idx[corpus[i]]

        for j in range(-window_size, window_size + 1):
            if j != 0:
                context = word2idx[corpus[i + j]]
                data.append((target, context))

    return data

"""# MODELS : CBOW"""

import torch
import torch.nn as nn

class CBOW(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super().__init__()
        self.embeddings = nn.Embedding(vocab_size, embed_dim)
        self.linear = nn.Linear(embed_dim, vocab_size)

    def forward(self, context):
        embeds = self.embeddings(context)
        embeds = embeds.mean(dim=1)
        out = self.linear(embeds)
        return out

"""# Skip-gram with Negative Sampling"""

class SkipGramNS(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super().__init__()
        self.input_embeddings = nn.Embedding(vocab_size, embed_dim)
        self.output_embeddings = nn.Embedding(vocab_size, embed_dim)

    def forward(self, target, pos_context, neg_context):
        # Corrected indentation
        target_emb = self.input_embeddings(target)
        pos_emb = self.output_embeddings(pos_context)
        neg_emb = self.output_embeddings(neg_context)

        pos_score = torch.sum(target_emb * pos_emb, dim=1)
        # Re-applying fix: squeeze() instead of squeeze(2)
        neg_score = torch.bmm(neg_emb, target_emb.unsqueeze(2)).squeeze()

        # Re-applying fix: Removed dim=1 from torch.sum for neg_score
        loss = -torch.log(torch.sigmoid(pos_score)) \
               - torch.sum(torch.log(torch.sigmoid(-neg_score)))

        return loss.mean()

"""# CBOW Training"""

def train_cbow(data, model, epochs=5, lr=0.005):

    import random
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        total_loss = 0

        random.shuffle(data)

        for context, target in data:

            context = torch.tensor([context])
            target = torch.tensor([target])

            output = model(context)
            loss = loss_fn(output, target)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss / len(data):.4f}")

"""# Skip-gram Training"""

def train_skipgram(data, model, vocab_size, neg_samples=5, epochs=5, lr=0.005):

    import random
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    for epoch in range(epochs):
        total_loss = 0

        random.shuffle(data)

        for target, context in data:

            target = torch.tensor([target])
            context = torch.tensor([context])

            neg_context = torch.randint(0, vocab_size, (1, neg_samples))

            loss = model(target, context, neg_context)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss / len(data):.4f}")

"""# EXPERIMENTS:"""

embedding_dims = [50, 100]
window_sizes = [2, 4]
neg_samples_list = [5, 10]

"""# CBOW Experiments"""

for dim in embedding_dims:
    for window in window_sizes:

        print(f"\nCBOW: dim={dim}, window={window}")

        data = generate_cbow_data(corpus, window)
        model = CBOW(vocab_size, dim)

        train_cbow(data, model)

"""# Skip-gram Experiments"""

for dim in embedding_dims:
    for window in window_sizes:
        for neg in neg_samples_list:

            print(f"\nSkipGram: dim={dim}, window={window}, neg={neg}")

            data = generate_skipgram_data(corpus, window)
            model = SkipGramNS(vocab_size, dim)

            train_skipgram(data, model, vocab_size, neg_samples=neg)

"""# Task 3

# SEMANTIC ANALYSIS
  EXTRACT EMBEDDINGS

For both models, we use the learned embeddings

 CBOW embeddings:
"""

embeddings = model.input_embeddings.weight.data

"""# Skip-gram embeddings:"""

embeddings = model.input_embeddings.weight.data

"""# COSINE SIMILARITY FUNCTION"""

import torch.nn.functional as F

def get_similar_words(word, embeddings, word2idx, idx2word, top_k=5):

    if word not in word2idx:
        print(f"{word} not in vocabulary")
        return

    word_idx = word2idx[word]
    word_vec = embeddings[word_idx]

    similarities = F.cosine_similarity(word_vec.unsqueeze(0), embeddings)

    # Get top-k (excluding itself)
    top_indices = similarities.argsort(descending=True)[1:top_k+1]

    return [idx2word[i.item()] for i in top_indices]

"""# NEAREST NEIGHBORS

Run for required words:
"""

words = ["research", "student", "phd", "exam"]

for w in words:
    neighbors = get_similar_words(w, embeddings, word2idx, idx2word)
    print(f"{w} → {neighbors}")

"""# ANALOGY TASK"""

def analogy(word_a, word_b, word_c, embeddings, word2idx, idx2word, top_k=5):

    if word_a not in word2idx or word_b not in word2idx or word_c not in word2idx:
        print("Word not in vocab")
        return

    vec = embeddings[word2idx[word_b]] - embeddings[word2idx[word_a]] + embeddings[word2idx[word_c]]

    similarities = F.cosine_similarity(vec.unsqueeze(0), embeddings)

    top_indices = similarities.argsort(descending=True)[1:top_k+1]

    return [idx2word[i.item()] for i in top_indices]

"""# RUN ANALOGIES"""

print("UG : BTech :: PG : ?")
print(analogy("ug", "btech", "pg", embeddings, word2idx, idx2word))

print("\nstudent : exam :: teacher : ?")
print(analogy("student", "exam", "teacher", embeddings, word2idx, idx2word))

print("\nresearch : paper :: teaching : ?")
print(analogy("research", "paper", "teaching", embeddings, word2idx, idx2word))

print("student" in word2idx)
print("exam" in word2idx)
print("teacher" in word2idx)
print("research" in word2idx)
print("paper" in word2idx)
print("teaching" in word2idx)

"""# Check top words"""

print(list(word2idx.keys())[:50])

print("research" in word2idx)
print("publication" in word2idx)
print("analysis" in word2idx)
print("model" in word2idx)
print("data" in word2idx)
print("algorithm" in word2idx)
print("learning" in word2idx)
print("training" in word2idx)

"""# RUN ANALOGIES"""

print("research : publication :: analysis : ?")
print(analogy("research", "publication", "analysis", embeddings, word2idx, idx2word))

print("\nmodel : data :: algorithm : ?")
print(analogy("model", "data", "algorithm", embeddings, word2idx, idx2word))

print("\nlearning : model :: training : ?")
print(analogy("learning", "model", "training", embeddings, word2idx, idx2word))

print("\nanalysis : data :: research : ?")
print(analogy("analysis", "data", "research", embeddings, word2idx, idx2word))

print("\nlearning : algorithm :: training : ?")
print(analogy("learning", "algorithm", "training", embeddings, word2idx, idx2word))

print("\nmodel : prediction :: data : ?")
print(analogy("model", "prediction", "data", embeddings, word2idx, idx2word))

"""# Task 4

VISUALIZATION
Visualize clusters
Compare CBOW vs Skip-gram

SELECT WORDS TO VISUALIZE
"""

words = [
    "research", "publication", "analysis",
    "model", "data", "learning", "training",
    "algorithm", "method", "result",
    "faculty", "student", "phd"
]

"""IMPORTANT CHECK"""

words = [w for w in words if w in word2idx]
print(words)

"""# GET VECTORS"""

import numpy as np

def get_word_vectors(words, embeddings, word2idx):
    vectors = []

    for w in words:
        vectors.append(embeddings[word2idx[w]].numpy())

    return np.array(vectors)

# Select top-N frequent words instead of manual list
top_n = 20
words = list(word2idx.keys())[:top_n]

# Add nearest neighbors of important words (for better clusters)
key_words = ["research", "student", "phd", "exam"]

for kw in key_words:
    if kw in word2idx:
        neighbors = get_similar_words(kw, embeddings, word2idx, idx2word, top_k=10)
        words.extend(neighbors)

# Remove duplicates
words = list(set(words))

def get_word_vectors(words, embeddings, word2idx):
    vectors = []

    for w in words:
        vectors.append(embeddings[word2idx[w]].detach().numpy())

    return np.array(vectors)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""# PCA VISUALIZATION"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

def plot_pca(words, vectors, title):

    pca = PCA(n_components=2)
    reduced = pca.fit_transform(vectors)

    plt.figure(figsize=(10,8))

    for i, word in enumerate(words):
        x, y = reduced[i]
        plt.scatter(x, y)
        plt.text(x+0.01, y+0.01, word)

    plt.title(title)
    plt.xlabel("PCA-1")
    plt.ylabel("PCA-2")
    plt.grid()
    plt.show()

"""# t-SNE VISUALIZATION"""

from sklearn.manifold import TSNE

def plot_tsne(words, vectors, title):

    tsne = TSNE(n_components=2, perplexity=5, random_state=42)
    reduced = tsne.fit_transform(vectors)

    plt.figure(figsize=(10,8))

    for i, word in enumerate(words):
        x, y = reduced[i]
        plt.scatter(x, y)
        plt.text(x+0.5, y+0.5, word)

    plt.title(title)
    plt.grid()
    plt.show()

"""# RUN FOR CBOW"""

# CBOW embeddings
embeddings_cbow = model.input_embeddings.weight.data

vectors = get_word_vectors(words, embeddings_cbow, word2idx)

plot_pca(words, vectors, "CBOW - PCA Visualization")
plot_tsne(words, vectors, "CBOW - t-SNE Visualization")

"""# RUN FOR SKIP-GRAM"""

# Skip-gram embeddings
embeddings_sg = model.input_embeddings.weight.data

vectors = get_word_vectors(words, embeddings_sg, word2idx)

plot_pca(words, vectors, "Skip-gram - PCA Visualization")
plot_tsne(words, vectors, "Skip-gram - t-SNE Visualization")

# Print embedding vector for a chosen word
chosen_word = "research"  # change to any word in your vocabulary

if chosen_word in word2idx:
    # Assuming the last trained model (either CBOW or SkipGramNS) is stored in 'model'
    # The embeddings are usually accessed via model.input_embeddings.weight
    vec = model.input_embeddings.weight[word2idx[chosen_word]].detach().cpu().numpy()
    vec_str = ", ".join(f"{v:.4f}" for v in vec)
    print(f"\n{chosen_word} - {vec_str}")
else:
    print(f"'{chosen_word}' not in vocabulary")

#  Use a fixed set of parameters for a new CBOW model with embed_dim=300
#  Let's choose window size = 4 for this example, based on previous experiments.
chosen_window_size = 4

# Initialize a new CBOW model
final_cbow_300 = CBOW(vocab_size, 300)

# Generate training data for CBOW
data_for_cbow_300 = generate_cbow_data(corpus, chosen_window_size)

# Train the CBOW model
print(f"\nTraining CBOW model with dim=300, window={chosen_window_size}")
train_cbow(data_for_cbow_300, final_cbow_300, epochs=10) # Using 10 epochs for this example

# Extract and print embeddings for a chosen word
chosen_word = "research"

if chosen_word in word2idx:
    # Access the embeddings directly from the trained CBOW model
    vec = final_cbow_300.embeddings.weight[word2idx[chosen_word]].detach().cpu().numpy()
    vec_str = ", ".join(f"{v:.4f}" for v in vec)
    print(f"\n{chosen_word} embedding (CBOW, dim=300): {vec_str}")
else:
    print(f"'{chosen_word}' not in vocabulary")

from collections import Counter

# Get word frequencies
word_counts = Counter(all_tokens)

# Get the top 10 most frequent words
top_10_words = word_counts.most_common(10)

# Format and print the output as requested
output_string = ", ".join([f"{word}, {count}" for word, count in top_10_words])
print(output_string)