# -*- coding: utf-8 -*-
"""nluprob2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z12B6tstYYgSYdOIaml8wuzDf8UZSnbw

# TAsk 0 Dataset created

# Loading and Cleaning the Dataset
"""

# ===== LOAD & CLEAN DATASET =====

with open("TrainingNames.txt", "r", encoding="utf-8") as f:
    raw_names = [line.strip() for line in f if line.strip()]

# Cleaning the names
names = []
for name in raw_names:
    name = name.lower()

    # Keep only alphabetic names
    if name.isalpha() and len(name) >= 3:
        names.append(name)

# Removing the duplicates
names = list(set(names))

print("Total names after cleaning:", len(names))
print("Sample names:", names[:10])

# Ensure exactly 1000 names
if len(names) > 1000:
    names = names[:1000]
elif len(names) < 1000:
    print("Less than 1000 names — consider adding more data")

print("Final dataset size:", len(names))

"""# TASK-1: MODEL IMPLEMENTATION

Loading the Data
"""

# ============================================================
# IMPORT REQUIRED LIBRARIES
# ============================================================
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# ============================================================
# DEVICE CONFIGURATION
# Use GPU I if it is available
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Load dataset
with open("TrainingNames.txt", "r") as f:
    names = [line.strip().lower() for line in f if line.strip()]

# Clean
names = list(set([n for n in names if n.isalpha() and len(n) >= 3]))

print("Dataset size:", len(names))

"""Vocabulary"""

# ============================================================
# BUILD CHARACTER VOCABULARY
# Including the special tokens for sequence modeling
# ============================================================

chars = sorted(set("".join(names)))
chars = ["<pad>", "<sos>", "<eos>"] + chars

# Character to index mapping
c2i = {c:i for i,c in enumerate(chars)}

# Character to index mapping
i2c = {i:c for c,i in c2i.items()}

#Special Tokens
PAD, SOS, EOS = c2i["<pad>"], c2i["<sos>"], c2i["<eos>"]
vocab_size = len(chars)

print("Vocab size:", vocab_size)

"""Dataset"""

# ============================================================
# Converts each name into sequence of indices
# ============================================================
class NameDataset(Dataset):
    def __init__(self, names):
        self.data = []
        for name in names:
            seq = [SOS] + [c2i[c] for c in name] + [EOS]
            self.data.append(torch.tensor(seq))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Pads sequences to same length in a batch
def collate_fn(batch):
    max_len = max(len(x) for x in batch)
    padded = torch.stack([
        torch.cat([x, torch.full((max_len-len(x),), PAD)])
        for x in batch
    ])
    return padded

dataset = NameDataset(names)
loader = DataLoader(dataset, batch_size=64, shuffle=True, collate_fn=collate_fn)

"""Hyperparameters"""

EMBED = 64
HIDDEN = 128
LAYERS = 2
LR = 0.003
EPOCHS = 20

"""# VANILLA RNN"""

class VanillaRNN(nn.Module):
    def __init__(self):
        super().__init__()
        # Embedding layer (character to vector)
        self.embed = nn.Embedding(vocab_size, EMBED, padding_idx=PAD)
        #rnn layer
        self.rnn = nn.RNN(EMBED, HIDDEN, LAYERS, batch_first=True, dropout=0.2)
        #output layer
        self.fc = nn.Linear(HIDDEN, vocab_size)

    def forward(self, x, h=None):
        x = self.embed(x)   #convert to embedding
        out, h = self.rnn(x, h) #pass through rnn
        out = self.fc(out)    #predict next char
        return out, h

    def init_hidden(self, b):
        return torch.zeros(LAYERS, b, HIDDEN).to(device)

    def generate(self, max_len=15, temp=0.8):
        self.eval()
        x = torch.tensor([[SOS]]).to(device)
        h = self.init_hidden(1)
        name = ""

        for _ in range(max_len):
            out, h = self.forward(x, h)
            #applying temperature sampling
            probs = torch.softmax(out[0, -1]/temp, dim=0)
            idx = torch.multinomial(probs, 1).item()
            if idx == EOS: break
            if idx not in [PAD, SOS]:
                name += i2c[idx]
            x = torch.tensor([[idx]]).to(device)
        return name

    def num_params(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

"""# BLSTM"""

class BLSTM(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, EMBED, padding_idx=PAD)
        #bidirectional lstm
        self.lstm = nn.LSTM(EMBED, HIDDEN, LAYERS,
                            batch_first=True,
                            bidirectional=True,
                            dropout=0.3)
        self.fc = nn.Linear(HIDDEN*2, vocab_size)

    def forward(self, x, h=None):
        x = self.embed(x)
        out, h = self.lstm(x, h)
        out = self.fc(out)
        return out, h

    def generate(self, max_len=15, temp=0.8):
        self.eval()
        x = torch.tensor([[SOS]]).to(device)
        h = None
        name = ""

        for _ in range(max_len):
            out, h = self.forward(x, h)
            probs = torch.softmax(out[0, -1]/temp, dim=0)
            idx = torch.multinomial(probs, 1).item()
            if idx == EOS: break
            if idx not in [PAD, SOS]:
                name += i2c[idx]
            x = torch.tensor([[idx]]).to(device)
        return name

    def num_params(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

"""# ATTENTION RNN"""

class Attention(nn.Module):
    def __init__(self):
        super().__init__()
        self.attn = nn.Linear(HIDDEN, HIDDEN)
        self.v = nn.Linear(HIDDEN, 1)

    def forward(self, rnn_out):
        scores = self.v(torch.tanh(self.attn(rnn_out)))
        weights = torch.softmax(scores, dim=1)
        context = torch.sum(weights * rnn_out, dim=1)
        return context


class AttnRNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, EMBED, padding_idx=PAD)
        self.rnn = nn.RNN(EMBED, HIDDEN, LAYERS, batch_first=True)
        self.attn = Attention()
        self.fc = nn.Linear(HIDDEN*2, vocab_size)

    def forward(self, x, h=None):
        x = self.embed(x)
        rnn_out, h = self.rnn(x, h)
        context = self.attn(rnn_out)
        context = context.unsqueeze(1).expand_as(rnn_out)
        out = torch.cat([rnn_out, context], dim=2)
        out = self.fc(out)
        return out, h

    def generate(self, max_len=15, temp=0.8):
        self.eval()
        x = torch.tensor([[SOS]]).to(device)
        h = None
        name = ""

        for _ in range(max_len):
            out, h = self.forward(x, h)
            probs = torch.softmax(out[0, -1]/temp, dim=0)
            idx = torch.multinomial(probs, 1).item()
            if idx == EOS: break
            if idx not in [PAD, SOS]:
                name += i2c[idx]
            x = torch.tensor([[idx]]).to(device)
        return name

    def num_params(self):
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

"""# TRAINING FUNCTION"""

def train(model):
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=LR)
    loss_fn = nn.CrossEntropyLoss(ignore_index=PAD)

    for epoch in range(EPOCHS):
        total_loss = 0

        for batch in loader:
            batch = batch.to(device)
            inp, tgt = batch[:, :-1], batch[:, 1:]

            out, _ = model(inp)

            loss = loss_fn(out.reshape(-1, vocab_size),
                           tgt.reshape(-1))

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5)
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}: {total_loss:.3f}")

    return model

"""# TRAIN ALL MODELS"""

rnn = train(VanillaRNN())
blstm = train(BLSTM())
attn = train(AttnRNN())

"""# Counting Parameters"""

print("\nNumber of Parameter:")
print("RNN:", rnn.num_params())
print("BLSTM:", blstm.num_params())
print("Attention:", attn.num_params())

print("\nSample Outputs:")
print("RNN:", [rnn.generate() for _ in range(10)])
print("BLSTM:", [blstm.generate() for _ in range(10)])
print("Attention:", [attn.generate() for _ in range(10)])

"""# TASK-2: QUANTITATIVE EVALUATION

Sampling
"""

def sample_top_k(logits, k=5, temperature=0.8):
    logits = logits / temperature
    probs = torch.softmax(logits, dim=0)

    top_probs, top_idx = torch.topk(probs, k)
    top_probs = top_probs / top_probs.sum()

    idx = torch.multinomial(top_probs, 1).item()
    return top_idx[idx].item()

print("\n" + "="*50)
print("TASK-2: QUANTITATIVE EVALUATION")
print("="*50)

def generate_names(model, num_samples=200, temperature=0.8):
    generated = []

    for _ in range(num_samples):
        name = model.generate(temp=temperature)

        # basic filtering only
        if len(name) >= 3 and name.isalpha():
            generated.append(name)
        else:
            generated.append(name)

    return generated


# Generate
rnn_gen = generate_names(rnn, 200,temperature=0.8)
blstm_gen = generate_names(blstm, 200, temperature=1.7)
attn_gen = generate_names(attn, 200,temperature=0.9)

print("Generated counts:", len(rnn_gen), len(blstm_gen), len(attn_gen))

"""METRICS"""

def novelty_rate(generated, training):
    training_set = set(training)
    return sum(1 for n in generated if n not in training_set) / len(generated)


def diversity(generated):
    return len(set(generated)) / len(generated)


print("\n=== FINAL METRICS ===")

rnn_nov = novelty_rate(rnn_gen, names)
rnn_div = diversity(rnn_gen)

blstm_nov = novelty_rate(blstm_gen, names)
blstm_div = diversity(blstm_gen)

attn_nov = novelty_rate(attn_gen, names)
attn_div = diversity(attn_gen)

print(f"RNN -> Novelty: {rnn_nov:.3f}, Diversity: {rnn_div:.3f}")
print(f"BLSTM -> Novelty: {blstm_nov:.3f}, Diversity: {blstm_div:.3f}")
print(f"Attention -> Novelty: {attn_nov:.3f}, Diversity: {attn_div:.3f}")

"""# Comparison Table"""

print("\nMODEL COMPARISON")
print("-"*50)
print(f"{'Model':<15} {'Novelty':<10} {'Diversity':<10}")
print("-"*50)

print(f"{'RNN':<15} {novelty_rate(rnn_gen, names):<10.3f} {diversity(rnn_gen):<10.3f}")
print(f"{'BLSTM':<15} {novelty_rate(blstm_gen, names):<10.3f} {diversity(blstm_gen):<10.3f}")
print(f"{'Attention':<15} {novelty_rate(attn_gen, names):<10.3f} {diversity(attn_gen):<10.3f}")

# Print
print("\n===== Vanilla RNN Samples =====")
for s in rnn_gen:
    print(s)

print("\n===== BLSTM Samples =====")
for s in blstm_gen:
    print(s)

print("\n===== Attention RNN Samples =====")
for s in attn_gen:
    print(s)

"""# Analyzing Realism"""

def is_realistic(name):
    vowels = "aeiou"

    # Conditions for realism
    if len(name) < 3 or len(name) > 12:
        return False

    vowel_count = sum(1 for c in name if c in vowels)
    if vowel_count == 0:
        return False

    if any(name.count(ch) > 3 for ch in set(name)):
        return False

    return True


def realism_score(samples):
    valid = sum(1 for n in samples if is_realistic(n))
    return valid / len(samples)


print("\n=== REALISM SCORES ===")
print(f"RNN: {realism_score(rnn_gen):.2f}")
print(f"BLSTM: {realism_score(blstm_gen):.2f}")
print(f"Attention: {realism_score(attn_gen):.2f}")

"""# Failure Cases"""

def get_failures(samples):
    failures = []

    for n in samples:
        if (
            len(n) < 3 or
            not n.isalpha() or
            any(n.count(ch) > 3 for ch in set(n))
        ):
            failures.append(n)

    return failures


print("\n=== FAILURE CASES ===")

print("\nRNN Failures:")
print(get_failures(rnn_gen))

print("\nBLSTM Failures:")
print(get_failures(blstm_gen))

print("\nAttention Failures:")
print(get_failures(attn_gen))

"""# Categorizing Failure Types"""

def categorize_failures(samples):
    categories = {
        "too_short": 0,
        "repetition": 0,
        "non_alpha": 0
    }

    for n in samples:
        # Check if the name is too short
        if len(n) < 3:
            categories["too_short"] += 1
        # Check if the name contains non-alphabetic characters
        if not n.isalpha():
            categories["non_alpha"] += 1
        # Check for excessive character repetition
        if any(n.count(ch) > 3 for ch in set(n)):
            categories["repetition"] += 1

    return categories


print("\n=== FAILURE TYPE ANALYSIS ===")

print("RNN:", categorize_failures(rnn_gen))
print("BLSTM:", categorize_failures(blstm_gen))
print("Attention:", categorize_failures(attn_gen))